import Link from "next/link";
import "@/styles/globals.css";
import { Fira_Code, Inter } from "next/font/google";
import { Providers } from "@/context/providers";
import clsx from "clsx";
import { NavigationEvents } from "@/components/navigation-events";
import { Suspense } from "react";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const fira_code = Fira_Code({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fira-code",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const htmlClasses = clsx(inter.variable, fira_code.variable, "antialiased");
  return (
    <html lang="en" className={htmlClasses}>
      <body className="min-h-screen bg-slate-50 text-slate-600 ">
        <Providers>
          <header className="max-width flex items-center justify-between text-sm font-medium">
            <div className="group">
              <Link href="/">
                ¡Hola!{" "}
                <span
                  role="img"
                  aria-label="waving hand emoji"
                  className="inline-block transition-transform group-hover:rotate-12"
                >
                  👋🏽
                </span>
              </Link>
            </div>
            <nav className="flex items-center justify-end gap-4 ">
              <Link href="/" className="py-4 hover:underline">
                Home
              </Link>
              <Link href="/about" className="py-4 hover:underline">
                About
              </Link>
            </nav>
          </header>
          {modal && modal}
          {children}
          <Suspense fallback={null}>
            <NavigationEvents />
          </Suspense>
        </Providers>
        <Script
          defer
          src="https://static.cloudflareinsights.com/beacon.min.js"
          data-cf-beacon='{"token": "f95f7928ffdf42758a3fcc9bede5d584"}'
        ></Script>
      </body>
    </html>
  );
}
