import Head from "next/head"
import Cover from "~components/cover"
import Skills from "~components/skills"
import WorkExperience from "~components/work-experience"

export default function Home() {
  return (
    <>
      <Head>
        <title>Joe Sanchez Jr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Cover />
      <div className="w-full max-w-screen-2xl mx-auto px-4 py-16 md:py-24">
        <p className="max-w-[60ch] font-serif text-[#141539] text-2xl sm:text-4xl">
          Creative developer with six years of experience building for the web. Dedicated to making beautiful and
          accessible digital products. Seeking to work with a team of good people making good things.
        </p>
      </div>

      <WorkExperience />
      <Skills />
    </>
  )
}
